package sportsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author HP
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SportGearTrack = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Background_welcome = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        Email_Username_Text = new javax.swing.JLabel();
        Password_Text = new javax.swing.JLabel();
        Email_Username = new javax.swing.JTextField();
        ForgotPassword = new javax.swing.JLabel();
        Log_In = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        SportGearTrack.setBackground(new java.awt.Color(213, 242, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Track");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("SportGear");

        javax.swing.GroupLayout SportGearTrackLayout = new javax.swing.GroupLayout(SportGearTrack);
        SportGearTrack.setLayout(SportGearTrackLayout);
        SportGearTrackLayout.setHorizontalGroup(
            SportGearTrackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SportGearTrackLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(SportGearTrackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SportGearTrackLayout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jLabel2)
                    .addContainerGap(281, Short.MAX_VALUE)))
        );
        SportGearTrackLayout.setVerticalGroup(
            SportGearTrackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SportGearTrackLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(SportGearTrackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SportGearTrackLayout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jLabel2)
                    .addContainerGap(605, Short.MAX_VALUE)))
        );

        Background_welcome.setBackground(new java.awt.Color(255, 255, 255));
        Background_welcome.setPreferredSize(new java.awt.Dimension(524, 720));

        Welcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Welcome.setText("Welcome!");

        Email_Username_Text.setText("E-mail/Username");

        Password_Text.setText("Password");

        Email_Username.setBackground(new java.awt.Color(237, 242, 247));
        Email_Username.setToolTipText("");
        Email_Username.addActionListener(this::Email_UsernameActionPerformed);

        ForgotPassword.setText("Forgot  Password?");

        Log_In.setBackground(new java.awt.Color(0, 0, 0));
        Log_In.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Log_In.setForeground(new java.awt.Color(255, 255, 255));
        Log_In.setText("Log In");
        Log_In.addActionListener(this::Log_InActionPerformed);

        Password.setBackground(new java.awt.Color(237, 242, 247));

        javax.swing.GroupLayout Background_welcomeLayout = new javax.swing.GroupLayout(Background_welcome);
        Background_welcome.setLayout(Background_welcomeLayout);
        Background_welcomeLayout.setHorizontalGroup(
            Background_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_welcomeLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(Background_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ForgotPassword)
                    .addComponent(Welcome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Email_Username)
                    .addComponent(Email_Username_Text, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password_Text, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Log_In, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(Password, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        Background_welcomeLayout.setVerticalGroup(
            Background_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_welcomeLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(Welcome)
                .addGap(30, 30, 30)
                .addComponent(Email_Username_Text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password_Text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ForgotPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Log_In, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SportGearTrack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Background_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SportGearTrack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Background_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Email_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_UsernameActionPerformed

    private void Log_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_InActionPerformed
        String username = Email_Username.getText();
        String password = Password.getText();

        try {

            String sql = "SELECT * FROM user_login WHERE username=? AND password=?";
            Connection conn = SQLConnection.connect();
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, username);
            pst.setString(2, password);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Login Successful! 😋");
                
                
                  // Open Dashboard
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
        
        // Close Login
        this.dispose();
        
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect Email or Password! ");
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_Log_InActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background_welcome;
    private javax.swing.JTextField Email_Username;
    private javax.swing.JLabel Email_Username_Text;
    private javax.swing.JLabel ForgotPassword;
    private javax.swing.JButton Log_In;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Password_Text;
    private javax.swing.JPanel SportGearTrack;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
